### PR TITLE
feature/kirkstone

### PR DESCRIPTION
**Pull request by thiesmoeller**
Hi Xilinx-Team,

I'm using your meta-layer quite some time now. 
With more and more platforms moving to kirkstone there was some pressure to migrate to the new environment ;-)

Take this as a draft pull request ( to inform you about the work done ). 
Main targets of the port are platforms other than Xilinx.
So there might some issues, that only get triggered in your kirkstone variant.... which I would be really interested to learn about..

All packages have been updated to the latest versions, that works with flit and setuptools as directly supported by kirkstone.

Regards,
Thies

### CODE REVIEW

**Comment by grsandeep85** [comment]
Hi @thiesmoeller,

Thanks for the patches. We will review and keep you posted.

**Comment by thiesmoeller** [comment]
have to still work on some dependency issues ...

**Comment by thiesmoeller** [comment]
As an additional package we might add into the packagegroup:
I always also install nodejs into the image, to get full functionality in jupyter-lab.

What is missing is https://matplotlib.org/ipympl/, which would give you nicer interactive plots.
This would be a bigger task to integrate, due to to the large number of npm dependencies to convert into yocto recipes.

**Comment by grsandeep85** [comment]
@thiesmoeller patches merged to kirkstone-next branch.

https://github.com/Xilinx/meta-jupyter/tree/kirkstone-next

**Comment by thiesmoeller** [comment]
@grsandeep85 thanks merging in my PR. Happy notebooking ;-) on kirkstone

**Pull request closed without merging**
