### PR TITLE
python3-anyio: added missing dependency

### PR DESCRIPTION
**Pull request by vermaete**
Added dependency to prevent fetching it in the compile step.

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>

### CODE REVIEW

**Comment by mhatle** [comment]
Thank you, we'll pull this into our internal version and test it.. Then will update the repository once it passes.

Should be one or two days.

**Comment by vermaete** [comment]
ping

**Comment by grsandeep85** [comment]
Hi @vermaete ,

We have pulled the patch to internal branch and CI is in progress.

**Comment by grsandeep85** [comment]
Patches merged to 2022.2 release. Refer 

https://github.com/Xilinx/meta-jupyter/commit/5c76bb7ab169e3e596cd247c48e76e84bb4c00e3

**Pull request closed without merging**
